[classifier]
raw_data_path = ''
training_data_path = ''
training_data_base_file = 'training.sqlite'
window_lengths = [1]
image_width = 224
image_height = 224
sampling_rate = 5000
buffer_image_fraction = 0.05

