freq_min = 50
start_search_window = -200e-3
end_search_window = 0e-3
start_refined_search_window = -10e-3
end_refined_search_window = 10e-3
search_resolution = 5e-4
pre_pick_window_len = 20e-3
post_pick_window_len = 20e-3
snr_threshold = 6
